### ISSUE TITLE
Not getting fixed 1000 foundation.

### ISSUE THREAD

**Issue by ActionHudson** [aekoch/DSP-Mods#1]
Mod doesn't seem to be working for me, when I unlock 'Environment Modifications' I don't get the fixed 1000 foundations.

De-activating and re-activating the mod doesn't help.
Crafted 1000 foundation and it still drains below 1000.

Game version Early Access 0.8.22.9331
Mod version 1.0.0 installed via r2modman

**Comment by maeeh** [comment]
Same here, mod seems to be non functional. Not only are the foundations not raised to 1000, the amount of sand is also not touched.

Game version Early Access 0.8.22.9331
Mod version 1.0.0 installed via r2modman

**Comment by aekoch** [comment]
Perhaps something went wrong with the upload process. I'm checking now.

**Comment by aekoch** [comment]
Nope...  This is 100% my fault.  Must not have tested it properly after cleaning up the code.  Fix is incoming.

**Comment by aekoch** [comment]
Updated to 1.0.1

Thank you both for reporting the problem.  Such an embarrassing mistake.

**Comment by maeeh** [comment]
You're my hero. Now it works. To be honest I do love DSP but I really hate the idea with the foundations. 

Thanx a lot for the fast fix

**Comment by ActionHudson** [comment]
Checked this morning and working fine.
Thanks a lot
